[package]
name = "lanceStudy"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow.workspace = true
arrow-array.workspace = true
futures.workspace = true
lance.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile = "3.5"
